# See docs for full reference
# https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service: ''

# app and org for use with dashboard.serverless.com
#app: ''
#org: ''

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.stage_vars.${self:provider.stage}.aws_profile}
  deploymentBucket:
    maxPreviousDeploymentArtifacts: 10
    blockPublicAccess: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: ${cf:unemployment-reminders-${self:provider.stage}.SecretsArn}
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:*:*:table/${self:custom.dynamo_db_table}"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
      Resource: "arn:aws:dynamodb:*:*:table/${self:custom.dynamo_db_table}/index/*"

custom:
  defaultStage: dev
  dynamo_db_table: unemployment-reminders
  stage_vars:
    dev:
      aws_profile: ''
      bot_base_url: ''
      bot_sms_number: ''
      custom_domain: ''
    stage:
      aws_profile: ''
      bot_base_url: ''
      bot_sms_number: ''
      custom_domain: ''
    prod:
      aws_profile: ''
      bot_base_url: ''
      bot_sms_number: ''
      custom_domain: ''
  # WSGI Plugin: https://github.com/logandk/serverless-wsgi
  wsgi:
    app: src/wsgi.app
    pythonBin: python3
    packRequirements: false
  # DynamoDB Local Plugin: https://github.com/99xt/serverless-dynamodb-local
  dynamodb:
    # We are using a separate container for this
    # https://github.com/99xt/serverless-dynamodb-local/issues/57#issuecomment-507005352
    start:
      host: dynamodb
      port: 8000
      noStart: true
    seed:
      init:
        sources:
          - table: ${self:custom.dynamo_db_table}
            sources: [./data/dynamo.seed.init.json]
    stages:
      - dev
  # Custom Domain Plugin: https://github.com/amplify-education/serverless-domain-manager
  customDomain:
    domainName: ${self:custom.stage_vars.${self:provider.stage}.custom_domain}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

plugins:
  - serverless-domain-manager
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-dynamodb-local

package:
  individually: false
  include:
    - '!./**'
    - 'src/**'
  exclude:
    - '**'

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
    timeout: 10
    memorySize: 1024
    environment:
      FLASK_ENV: ${self:provider.stage}
      SECRETS_MANAGER_SECRET_ARN: ${cf:unemployment-reminders-${self:provider.stage}.SecretsArn}
      BOT_BASE_URL: ${self:custom.stage_vars.${self:provider.stage}.bot_base_url}
      BOT_SMS_NUMBER: ${self:custom.stage_vars.${self:provider.stage}.bot_sms_number}
      API_GATEWAY_BASE_PATH: ${self:provider.stage}
  poller:
    handler: src/poller.lambda_handler
    events:
      # Every 5th minute past every hour from 13 through 17 (UTC) on every day-of-week from Monday through Friday.
      - schedule:
          rate: cron(*/5 13-17 ? * MON-FRI *)
          enabled: true
      # This is useful for testing. Disabled by default
      - schedule:
          rate: rate(1 minute)
          enabled: false
    timeout: 600
    memorySize: 1024
    environment:
      FLASK_ENV: ${self:provider.stage}
      SECRETS_MANAGER_SECRET_ARN: ${cf:unemployment-reminders-${self:provider.stage}.SecretsArn}
      BOT_SMS_NUMBER: ${self:custom.stage_vars.${self:provider.stage}.bot_sms_number}

resources:
  Resources:
    RemindersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          # E.164 phone number. https://www.twilio.com/docs/glossary/what-e164
          - AttributeName: phone_number
            AttributeType: S
          # UTC ISO 8601 date
          - AttributeName: next_alert_at
            AttributeType: S
          # 1,0 Flag the alert as in progress
          - AttributeName: in_progress
            AttributeType: N
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: gsi_queue
            KeySchema:
              - AttributeName: in_progress
                KeyType: HASH
              - AttributeName: next_alert_at
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                # monday, tuesday, wednesday, thursday, friday
                - alert_day
                # America/Chicago
                - timezone
                # UTC ISO 8601 date.
                - alert_time
              ProjectionType: INCLUDE
        KeySchema:
          - AttributeName: phone_number
            KeyType: HASH
        TableName: ${self:custom.dynamo_db_table}
