version: 2
jobs:
  build:
    working_directory: ~/unemployment-reminders
    docker:
      - image: circleci/python:3.9.13
        environment:
          FLASK_ENV: test
          SECRET_KEY: ""
          TWILIO_ACCOUNT_SID: "invalid"
          TWILIO_AUTH_TOKEN: "invalid"
          DYNAMODB_ENDPOINT: "http://localhost:8000"
          AWS_DEFAULT_REGION: "us-east-1"
    steps:
      - checkout
      - run:
          command: |
            sudo pip3 install -r requirements.txt
            sudo pip3 install -r requirements-dev.txt
      - run:
          command: |
            nose2 -v
